### ISSUE TITLE
Concurrent createrepo runs can race and cause repo metadata corruption

### ISSUE THREAD

**Issue by euanh** [xenserver/planex#150]
Probably caused by non-atomic updates of repo metadata.

```
Traceback (most recent call last):
File "/usr/bin/planex-cache", line 9, in <module>
load_entry_point('planex==0.6.0', 'console_scripts', 'planex-cache')()
File "/usr/lib/python2.7/site-packages/planex-0.6.0-py2.7.egg/planex/cache.py", line 239, in
_main
main(sys.argv[1:])
File "/usr/lib/python2.7/site-packages/planex-0.6.0-py2.7.egg/planex/cache.py", line 217, in
main
pkg_hash = get_srpm_hash(srpm, yumbase, mock_config)
File "/usr/lib/python2.7/site-packages/planex-0.6.0-py2.7.egg/planex/cache.py", line 156, in
get_srpm_hash
pkgs = yumbase.pkgSack.returnNewestByNameArch(patterns=[req])
File "/usr/lib/python2.7/site-packages/yum/packageSack.py", line 520, in
returnNewestByNameArch
pkgs = calr("returnNewestByNameArch", naTup, patterns, ignore_case)
File "/usr/lib/python2.7/site-packages/yum/packageSack.py", line 595, in
_computeAggregateListResult
sackResult = apply(method, args)
File "/usr/lib/python2.7/site-packages/yum/sqlitesack.py", line 46, in newFunc
return func(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/yum/sqlitesack.py", line 1472, in
returnNewestByNameArch
ignore_case)
File "/usr/lib/python2.7/site-packages/yum/packageSack.py", line 951, in
returnNewestByNameArch
ignore_case=ignore_case)
File "/usr/lib/python2.7/site-packages/yum/sqlitesack.py", line 1669, in returnPackages
pkgobjlist = self._buildPkgObjList(repoid, patterns, ignore_case)
File "/usr/lib/python2.7/site-packages/yum/sqlitesack.py", line 46, in newFunc
return func(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/yum/sqlitesack.py", line 1628, in _buildPkgObjList
return self.searchNames(patterns)
File "/usr/lib/python2.7/site-packages/yum/sqlitesack.py", line 57, in newFunc
raise Errors.RepoError, str(e)
yum.Errors.RepoError: database disk image is malformed
/usr/share/planex/Makefile.rules:69: recipe for target
'_build/RPMS/x86_64/ocaml402-ocaml-text-0.7.1-2.el6.x86_64.rpm' failed
make: *** [_build/RPMS/x86_64/ocaml402-ocaml-text-0.7.1-2.el6.x86_64.rpm] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by euanh** [comment]
The fix for this is probably to write a wrapper for createrepo which ensures that changes are atomic by writing to a different directory and swapping them in.

**Comment by euanh** [comment]
PR #180 should help, but the root of the problem is yum reusing its cache directory in /tmp/yum-$userid-$random, leading to write-after-write conflicts between concurrent planex-cache runs.

**Comment by euanh** [comment]
Still encountering problems with concurrent planex-cache runs...

**Comment by simonjbeaumont** [comment]
booo.

**Comment by euanh** [comment]
```
Traceback (most recent call last):
  File "/usr/bin/planex-cache", line 9, in <module>
    load_entry_point('planex==0.6.0', 'console_scripts', 'planex-cache')()
  File "/usr/lib/python2.7/site-packages/planex-0.6.0-py2.7.egg/planex/cache.py", line 246, in _main
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/planex-0.6.0-py2.7.egg/planex/cache.py", line 217, in main
    setup_yumbase(yumbase, loopback_repo)
  File "/usr/lib/python2.7/site-packages/planex-0.6.0-py2.7.egg/planex/cache.py", line 77, in setup_yumbase
    yumbase.repos.populateSack(cacheonly=True)
  File "/usr/lib/python2.7/site-packages/yum/repos.py", line 344, in populateSack
    self.doSetup()
  File "/usr/lib/python2.7/site-packages/yum/repos.py", line 157, in doSetup
    self.retrieveAllMD()
  File "/usr/lib/python2.7/site-packages/yum/repos.py", line 96, in retrieveAllMD
    downloading = repo._commonRetrieveDataMD_list(mdtypes)
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 1594, in _commonRetrieveDataMD_list
    os.rename(local, local + '.old.tmp')
OSError: [Errno 2] No such file or directory
/usr/share/planex/Makefile.rules:113: recipe for target '_build/RPMS/x86_64/ocaml-fieldslib-109.20.00-1.fc21.x86_64.rpm' failed
```

**Comment by euanh** [comment]
I think that the best way to fix this is to run createrepo within the mock chroot before starting the package build.  This is what cowbuilder does for Debian packages and it should make it impossible for two concurrent createrepo jobs to interfere with each other.

**Comment by euanh** [comment]
Sadly I don't think that running createrepo in the chroot will help.   cowbuilder creates a chroot and then runs apt-get install within the chroot, whereas mock pushes the required packages in from the outside.   The repository is not mounted in the chroot, so there is no opportunity to run createrepo inside it.
