### ISSUE TITLE
The error message from 'planex-pin update' when the treeish isn't specified is unhelpful

### ISSUE THREAD

**Issue by jonludlam** [xenserver/planex#199]
No `#master` specified on the repo path leads to:

```
# planex-pin add SPECS/foo.spec /repos/myrepo
# planex-pin update
Traceback (most recent call last):
  File "/usr/bin/planex-pin", line 9, in <module>
    load_entry_point('planex==0.6.0', 'console_scripts', 'planex-pin')()
  File "/usr/lib/python2.7/site-packages/planex-0.6.0-py2.7.egg/planex/pin.py", line 341, in _main
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/planex-0.6.0-py2.7.egg/planex/pin.py", line 334, in main
    args.func(args)
  File "/usr/lib/python2.7/site-packages/planex-0.6.0-py2.7.egg/planex/pin.py", line 159, in update
    src_version = describe(repo, treeish if treeish else None)
  File "/usr/lib/python2.7/site-packages/planex-0.6.0-py2.7.egg/planex/pin.py", line 34, in describe
    sha = run(cmd)['stdout'].strip()
  File "/usr/lib/python2.7/site-packages/planex-0.6.0-py2.7.egg/planex/util.py", line 60, in run
    (" ".join([pipes.quote(word) for word in cmd])))
  File "/usr/lib64/python2.7/pipes.py", line 269, in quote
    for c in file:
TypeError: 'NoneType' object is not iterable
```

**Comment by euanh** [comment]
Superseded by reimplementation of pinning using patch queues.
