### ISSUE TITLE
planex-make-srpm does not handle pinned spec files correctly

### ISSUE THREAD

**Issue by euanh** [xenserver/planex#265]
If a package is pinned, `planex-make-srpm` is called with the pinned SPEC file as follows:
```
sh-4.2# planex-make-srpm --topdir _build --dist .fc21 _build/PINS/planex.spec _build/SOURCES/planex-0.7.3+6+g3d11454.tar.gz
```

It tries to copy the spec file to `$TMPDIR/PINS/planex.spec`, but the copy fails because this directory doesn't exist (we only create `SPECS` and `_build`).   The following output was obtained by printing th arguments to `copyfile` and removing the `IOError` exception handler:
```
copyfile(_build/PINS/planex.spec, /tmp/tmpAABeJX/_build/PINS/planex.spec)
Traceback (most recent call last):
  File "/usr/bin/planex-make-srpm", line 9, in <module>
    load_entry_point('planex==0.7.2', 'console_scripts', 'planex-make-srpm')()
  File "/usr/lib/python2.7/site-packages/planex-0.7.2-py2.7.egg/planex/makesrpm.py", line 151, in _main
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/planex-0.7.2-py2.7.egg/planex/makesrpm.py", line 124, in main
    copyfile(specfile, tmp_specfile)
  File "/usr/lib64/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/tmp/tmpAABeJX/_build/PINS/planex.spec'
```

**Comment by euanh** [comment]
Fixed by #266.
